name: Deploy UI to dev

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    uses: kulmajaba/figma-better-color-picker/.github/workflows/deploy-ui.yml@develop
    with:
      node-version: '18.x'
      deploy-path: 'sites/colorpicker-dev'
    secrets: inherit